sudo: required
services:
  - docker

before_install:
  - docker build -t hugo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hugo/react-test npm test

after_success:
  - docker build -t hugo/multi-client ./client
  - docker build -t hugo/multi-nginx ./nginx
  - docker build -t hugo/multi-server ./server
  - docker build -t hugo/multi-worker ./worker
  #Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push hugo/multi-client
  - docker push hugo/multi-nginx
  - docker push hugo/multi-server
  - docker push hugo/multi-worker
