sudo: required
services:
  - docker

before_install:
  - docker build -t hugo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hugo/react-test npm test

after_success:
  - docker build -t hugo/multi-client ./client
  - docker build -t hugo/multi-nginx ./nginx
  - docker build -t hugo/multi-server ./server
  - docker build -t hugo/multi-worker ./worker
  #Docker login
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  # Push images to Docker Hub
  - docker push hugo/multi-client
  - docker push hugo/multi-nginx
  - docker push hugo/multi-server
  - docker push hugo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "complex"
  env: "Complex-env"
  bucket_name: "elasticbeanstalk-eu-west-1-458340884914"
  bucket_path: "complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
